#You can eidt the color scheme in source/css/_base/variable.styl

photo: ./me.jpg

email: 
twitter: VF4rcy
facebook: 
googleplus: 
github: https://github.com/vfarcy
pinterest: 
linkedin: http://fr.linkedin.com/in/vfarcy/
instagram: 
zhihu: 
weibo: 
renren: 


addthis:
  enable: false
  pubid:
  facebook: false
  twitter: true
  google: true
  pinterest: true

fancybox: true

#
bighomepage: true

#Use cdnjs' CDN
usecdn: false

google_analytics: UA-46393541-1
rss: /atom.xml

forvirgo: true
