#You can eidt the color scheme in source/css/_base/variable.styl

photo: 

email: 
twitter: VF4rcy
facebook: 
googleplus: 
github: vfarcy
pinterest: 
linkedin: vfarcy/
instagram: 
zhihu: 
weibo: 
renren: 


addthis:
  enable: false
  pubid:
  facebook: false
  twitter: true
  google: true
  pinterest: true

fancybox: true

#
bighomepage: true

#Use cdnjs' CDN
usecdn: false

google_analytics: UA-46393541-1
rss: /atom.xml

forvirgo: true
