# Header
menu:
  Home: /hexoskelet
  Archives: /hexoskelet/archives
rss: http://feeds.feedburner.com/vfarcy

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: favicon.png