# Header
menu:
#  Home: /hexoskelet
#  Archives: /hexoskelet/archives
  Home: /
  Archives: /archives
rss: http://feeds.feedburner.com/vfarcy?format=xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-2992740-18
favicon: favicon.png