# Header
menu:
  Home: .
  Archives: /hexoskelet/archives
  About: /hexoskelet/about
rss: /hexoskelet/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: favicon.png